#!/bin/sh
gap=30

bspc config top_padding        63
bspc config bottom_padding     $gap
bspc config left_padding       $gap
bspc config right_padding      $gap
bspc config window_gap         30

bspc config gapless_monocle   false

bspc config border_width            0
bspc config split_ratio             0.52
bspc config focus_follows_pointer   true

bspc config normal_border_color   "#000000"
bspc config focused_border_color  "#000000"

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#workspaces_multimonitor &

#bspc rule -a firefox desktop=I

bspc config external_rules_command /usr/bin/pseudo_automatic_mode

pkill sxhkd
pkill dunst
pkill picom

sxhkd &
feh --no-fehbg --bg-fill "$HOME/Wallpaper/nuvens.jpg" &
picom &
dunst &
$HOME/.config/polybar/launch.sh &